ValueSet: DAK.DT.IMMZ.D5.DT.HPVcontraindications
Title: "Decision Table for DAK.DT.IMMZ.D5.DT.HPVcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DAK.DT.IMMZ.D5.DT.HPVcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* include DAK#"The client has history of severe allergic reactions"
* include DAK#"HPV vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DAK#"Do not vaccinate client with HPV if client has history of a severe allergic reaction after a previous HPV vaccine dose, or to a component of the vaccine."

