ValueSet: DAK.DT.IMMZ.D5.DT.DTPcontraindications
Title: "Decision Table for DAK.DT.IMMZ.D5.DT.DTPcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DAK.DT.IMMZ.D5.DT.DTPcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* include DAK#"The client currently has a severe acute illness"
* include DAK#"Tetanus vaccination is contraindicated"
* include DAK#"Do not vaccinate client with tetanus as tetanus vaccination is contraindicated for clients with severe acute illness"

