ValueSet: DAK.DT.IMMZ.D5.DT.TBEcontraindications
Title: "Decision Table for DAK.DT.IMMZ.D5.DT.TBEcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DAK.DT.IMMZ.D5.DT.TBEcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* include DAK#"The client has moderate to severe fever"
* include DAK#"Clinical judgement is required. Create a clinical note"
* include DAK#"Consider postponing the vaccination if the client has fever > 38.5°C or other signs of serious disease. Consider risks of vaccination and make a clinical judgement."

