ValueSet: DD
Title: "Decision Table"
Description:  "Value Set for Decision Table. Autogenerated from DAK artifacts"
Usage: #definition
* publisher = "WHO"
* experimental = false
* version = "0.2.0"
* ^status = #active
* ^experimental = false
* include codes from system DD

