ValueSet: DecisionTable.HepatitisB
Title: "Decision Logic For Decision Table IMMZ.D5.DT.HepatitisBcontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.HepatitisBcontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DecisionTable#"The client has history of severe allergic reactions"
* include DecisionTable#"Hepatitis B vaccination could be contraindicated. Clinical judgement is required. Create a clinical note."
* include DecisionTable#"Do not vaccinate client with hepatitis B if the client had a history of serious allergic reactions to any of the vaccine components. Allergy to yeast is considered a contraindication to immunization with yeast-produced hepatitis B-containing vaccine."

