ValueSet: DecisionLogicTableMeningococcal
Title: "Decision Logic For Decision Table IMMZ.D5.DT.Meningococcalcontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.Meningococcalcontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DecisionLogic#"The client has history of severe allergic reactions"
* include DecisionLogic#"Meningococcal vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DecisionLogic#"Do not vaccinate client with meningococcal if client has history of severe allergic reaction to any component of the meningococcal vaccine."

