ValueSet: DecisionTable.IMMZ.D5.DT.Meningococcalcontraindications
Title: "Decision Logic For Decision Table IMMZ.D5.DT.Meningococcalcontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.Meningococcalcontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DecisionTable#"The client has history of severe allergic reactions"
* include DecisionTable#"Meningococcal vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DecisionTable#"Do not vaccinate client with meningococcal if client has history of severe allergic reaction to any component of the meningococcal vaccine."

