ValueSet: DecisionTable.IMMZ.D5.DT.Hibcontraindications
Title: "Decision Logic For Decision Table IMMZ.D5.DT.Hibcontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.Hibcontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DecisionTable#"The client has a history of severe allergic reactions"
* include DecisionTable#"Hib vaccination could be contraindicated. Clinical judgement is required. Create a clinical note."
* include DecisionTable#"Do not vaccinate client with Hib conjugate vaccine if client has had allergic reaction or known allergies to any component of the vaccine."

