ValueSet: DT-IMMZ.D5.DT.HepatitisBcontraindications
Title: "Decision Table for IMMZ.D5.DT.HepatitisBcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for IMMZ.D5.DT.HepatitisBcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has history of severe allergic reactions"
* include DT#"Hepatitis B vaccination could be contraindicated. Clinical judgement is required. Create a clinical note."
* include DT#"Do not vaccinate client with hepatitis B if the client had a history of serious allergic reactions to any of the vaccine components. Allergy to yeast is considered a contraindication to immunization with yeast-produced hepatitis B-containing vaccine."

