ValueSet: DT-IMMZ.D5.DT.Malariacontraindications
Title: "Decision Logic For Decision Table IMMZ.D5.DT.Malariacontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.Malariacontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has hypersensitivity to any of the vaccine components"
* include DT#"Malaria vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DT#"Do not vaccinate client with RTS,S/AS01 vaccine if client has severe hypersensitivity to any of the vaccine components."

