ValueSet: DT-IMMZ.D5.DT.Rabiescontraindications
Title: "Decision Logic For Decision Table IMMZ.D5.DT.Rabiescontraindications"
Description:  "Value Set for Decision Logic For Decision Table IMMZ.D5.DT.Rabiescontraindications. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has history of severe allergic reactions"
* include DT#"Clinical judgement is required. Create a clinical note"
* include DT#"Check if the client has a history of severe hypersensitivity to any of the components or to excipients listed by the vaccine manufacturer. If so, provide an alternative rabies vaccine product for PreP."

