ValueSet: DT-IMMZ.D5.DT.Meningococcalcontraindications
Title: "Decision Table for IMMZ.D5.DT.Meningococcalcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for IMMZ.D5.DT.Meningococcalcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has history of severe allergic reactions"
* include DT#"Meningococcal vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DT#"Do not vaccinate client with meningococcal if client has history of severe allergic reaction to any component of the meningococcal vaccine."

