ValueSet: DT.DT.IMMZ.D5.DT.Rotaviruscontraindications
Title: "Decision Table for DT.IMMZ.D5.DT.Measlescontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DT.IMMZ.D5.DT.Measlescontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client is pregnant"
* include DT#"Measles vaccination contraindicated"
* include DT#"Do not vaccinate client with measles as measles vaccination is contraindicated for pregnant client."
* include DT#"The client has history of anaphylactic reactions"
* include DT#"Measles vaccination could be contraindicated. Clinical judgement required. Create a clinical note"
* include DT#"Do not vaccinate client with measles if client has history of anaphylactic reaction to any component of the vaccine (e.g. neomycin or gelatin)."
* include DT#"The client has history of severe allergic reactions"
* include DT#"Clinical judgement required. Create a clinical note"
* include DT#"Do not vaccinate client with measles if client has history of severe allergic reactions to any component of the vaccine (e.g. neomycin or gelatin)."
* include DT#"The client is severely immunosuppressed"
* include DT#"Do not vaccinate client with measles as measles vaccination is contraindicated for severely immunosuppressed client."
* include DT#"The client has a symptomatic HIV infection"
* include DT#"Client has symptomatic HIV infection. Measles vaccination may be considered if the client is not severely immunosuppressed according to conventional definitions, consider risks of vaccination and make a clinical judgement."

