ValueSet: DT.IMMZ.D5.DT.TBEcontraindications
Title: "Decision Table for DT.IMMZ.D5.DT.TBEcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DT.IMMZ.D5.DT.TBEcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has moderate to severe fever"
* include DT#"Clinical judgement is required. Create a clinical note"
* include DT#"Consider postponing the vaccination if the client has fever > 38.5°C or other signs of serious disease. Consider risks of vaccination and make a clinical judgement."

