ValueSet: DT.IMMZ.D5.DT.DTPcontraindications
Title: "Decision Table for DT.IMMZ.D5.DT.DTPcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DT.IMMZ.D5.DT.DTPcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client currently has a severe acute illness"
* include DT#"Tetanus vaccination is contraindicated"
* include DT#"Do not vaccinate client with tetanus as tetanus vaccination is contraindicated for clients with severe acute illness"

