ValueSet: DT.IMMZ.D5.DT.JEcontraindications
Title: "Decision Table for DT.IMMZ.D5.DT.JEcontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DT.IMMZ.D5.DT.JEcontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* include DD#"The client is currently pregnant"
* include DD#"Clinical judgement is required. Create a clinical note"
* include DD#"The client is currently pregnant, consider risks of vaccination and make a judgement. Inactivated Vero cell-derived vaccines are preferred over live attenuated or live recombinant vaccines."

