ValueSet: DT.IMMZ.D5.DT.Seasonalinfluenzacontraindications
Title: "Decision Table for DT.IMMZ.D5.DT.Seasonalinfluenzacontraindications. Autogenerated from DAK artifacts"
Description:  "Value Set for Decision Table for DT.IMMZ.D5.DT.Seasonalinfluenzacontraindications. Autogenerated from DAK artifacts. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = false
* include DT#"The client has a history of severe allergic reactions after a previous dose or to a vaccine component"
* include DT#"Seasonal influenza vaccination could be contraindicated. Clinical judgement is required. Create a clinical note"
* include DT#"Do not vaccinate client with seasonal influenza if client has had a severe allergic reaction (e.g. anaphylaxis) after a previous dose or to a vaccine component."

