openapi: 3.0.3
info:
  title: IMMZ.D1.Capture or update client history API
  description: Data elements for the IMMZ.D1.Capture or update client history Data
    Dictionary Activity.
  version: 1.0.0
paths:
  /StructureDefinition-IMMZ_D1_Capture_or_update_client_history.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-IMMZ_D1_Capture_or_update_client_history
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-IMMZ_D1_Capture_or_update_client_history.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-IMMZ_D1_Capture_or_update_client_history
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-IMMZ_D1_Capture_or_update_client_history.schema.json
components:
  schemas:
    StructureDefinition-IMMZ_D1_Capture_or_update_client_history:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/immunizations/StructureDefinition-IMMZ_D1_Capture_or_update_client_history.schema.json
      title: IMMZ.D1.Capture or update client history
      description: Data elements for the IMMZ.D1.Capture or update client history
        Data Dictionary Activity.
      type: object
      properties:
        IMMZD1:
          type: array
          items:
            type: object
            description: 'FHIR '
          description: Data elements for the IMMZ.D1.Capture or update client history
            Data Dictionary Activity.
        patient:
          type: object
          description: The patient.
        birthDose:
          type: boolean
          description: Indicates if the client received a dose within 24 hours of
            birth. Whether a birth dose is counted as part of the primary series will
            depend on the antigen
        typeOfDose:
          type: object
          description: The type of dose in a series that the client received
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE258.schema.json
            display:
              type: string
        completedThePrimaryVaccinationSeries:
          type: boolean
          description: Indicates if the client has completed the primary vaccination
            series of a product/antigen. If the client has not yet completed their
            primary series, it means they may be expected to receive more doses to
            complete their vaccination regimen for the respective product/antigen
        completedTheBoosterSeries:
          type: boolean
          description: Indicates if the client has completed the booster series of
            a product/antigen
        dateWhenPrimaryVaccinationSeriesWasCompleted:
          type: string
          format: date
          description: The date when the client completed the primary vaccination
            series (per product/antigen)
        hivStatus:
          type: object
          description: The current HIV status of the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE204.schema.json
            display:
              type: string
        pretermBirth:
          type: boolean
          description: The infant was preterm; the mother gave birth to the infant
            when gestational age was less than 37 weeks
        immunocompromised:
          type: boolean
          description: The client is known to be immunocompromised. This means the
            client has a weakened immune system and having a reduced ability to fight
            infections and other diseases
        currentlyOnArt:
          type: boolean
          description: The client is currently receiving antiretroviral therapy (ART)
        typeOfTbInfectionTestPerformed:
          type: object
          description: The type of tuberculosis (TB) infection test performed
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE243.schema.json
            display:
              type: string
        tbInfectionTestResult:
          type: object
          description: Records the result of the TB infection test
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE246.schema.json
            display:
              type: string
        immunologicallyStable:
          type: boolean
          description: The client is living with HIV and is immunologically stable
            with CD4 count or percentage above a minimum as defined in the HIV guidelines
        clinicallyWell:
          type: boolean
          description: The client is living with HIV and is clinically well, as defined
            in HIV guidelines and WHO clinical staging
        birthWeightInGrams:
          type: number
          description: Represents the client's birth weight value measures in grams
        typeOfPoliovirusDose:
          type: object
          description: The type of the poliovirus vaccine dose administered to the
            client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE212.schema.json
            display:
              type: string
        artStartDate:
          type: string
          format: date
          description: The date on which the client started or restarted ART
        highRiskOfPneumococcalInfection:
          type: boolean
          description: The client is at high risk for pneumococcal infection because
            of underlying medical conditions (i.e. HIV infection or sickle-cell disease)
        typeOfJeDose:
          type: object
          description: The type of Japanese encephalitis (JE) vaccine dose administered
            to the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE216.schema.json
            display:
              type: string
        typeOfTbeDose:
          type: object
          description: The type of tick-borne encephalitis (TBE) vaccine dose administered
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE220.schema.json
            display:
              type: string
        typeOfTyphoidDose:
          type: object
          description: The type of typhoid vaccine dose administered to the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE225.schema.json
            display:
              type: string
        typeOfCholeraDose:
          type: object
          description: The type of cholera vaccine dose administered to the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE229.schema.json
            display:
              type: string
        typeOfMeningococcalDose:
          type: object
          description: The type of meningococcal vaccine dose administered to the
            client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE232.schema.json
            display:
              type: string
        ageInMonthsWhenClientReceivedFirstMeningococcalDose:
          type: number
          description: The age in months when client received their first meningococcal
            dose
        typeOfHepatitisADose:
          type: object
          description: The type of hepatitis A-containing vaccine dose administered
            to the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE237.schema.json
            display:
              type: string
        typeOfHepatitisBDose:
          type: object
          description: The type of hepatitis B-containing vaccine dose administered
            to the client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE254.schema.json
            display:
              type: string
        vnaLevel:
          type: number
          description: Vaccine-induced neutralizing antibody (VNA) level, measured
            as a serum antibody concentration from the result of the concentrated,
            purified cell culture-derived and embryonated egg-based rabies vaccines
            (CCEEV)
        riskOfOccupationalExposureToRabiesVirus:
          type: boolean
          description: Professional at risk of occupational exposure to rabies virus,
            particularly animal health workers. Also considered for medical professionals
            who regularly provide care to persons with rabies
        dengueSerostatus:
          type: object
          description: Indicates the result of a serological test determining whether
            the client has antibodies against the dengue virus
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE241.schema.json
            display:
              type: string
        vaccineType:
          type: array
          items:
            type: object
            description: Coding from ValueSet IMMZ.Z.VS
            properties:
              system:
                type: string
              code:
                $ref: ValueSet-IMMZ.Z.VS.schema.json
              display:
                type: string
          minItems: 1
          description: Vaccine type/category that was administered or was to be administered.
            Any vaccine code available in the IMMZ.Z Vaccine library list of codes
            applies in this data element
        dateAndTimeOfVaccination:
          type: string
          format: date-time
          description: Represents the visit/encounter date, which is the date and
            time when each vaccine was administered to the client
        contactDate:
          type: string
          format: date-time
          description: The date and time of the client's contact
        ancContactNumber:
          type: integer
          description: The antenatal care (ANC) contact or visit number
        doseNumber:
          type: integer
          description: Vaccine dose number including dose number within series
      required:
      - patient
      - typeOfDose
      - vaccineType
      - dateAndTimeOfVaccination
      - doseNumber
      fhir:logicalModel: http://smart.who.int/immunizations/StructureDefinition/IMMZD1
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
