openapi: 3.0.3
info:
  title: IMMZ.D2.Determine required vaccination(s) API
  description: Data elements for the IMMZ.D2.Determine required vaccination(s) Data
    Dictionary Activity.
  version: 1.0.0
paths:
  /StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_.schema.json
components:
  schemas:
    StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/immunizations/StructureDefinition-IMMZ_D2_Determine_required_vaccination_s_.schema.json
      title: IMMZ.D2.Determine required vaccination(s)
      description: Data elements for the IMMZ.D2.Determine required vaccination(s)
        Data Dictionary Activity.
      type: object
      properties:
        IMMZD2:
          type: array
          items:
            type: object
            description: 'FHIR '
          description: Data elements for the IMMZ.D2.Determine required vaccination(s)
            Data Dictionary Activity.
        patient:
          type: object
          description: The patient.
        immunizationRecommendationStatus:
          type: object
          description: The current status or recommendation for a specific immunization
            for an client
          properties:
            system:
              type: string
            code:
              $ref: ValueSet-IMMZ.D.DE156.schema.json
            display:
              type: string
      required:
      - patient
      - immunizationRecommendationStatus
      fhir:logicalModel: http://smart.who.int/immunizations/StructureDefinition/IMMZD2
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
