CodeSystem: DecisionLogic
Title: "Decision Logic"
Description:  "CodeSystem for Decision Logic. Autogenerated from DAK artifacts"
* ^experimental = false
* ^caseSensitive = false
* ^status = #active
* ^property[+].code = #"table"* ^property[=].description = Decision Table ID
* ^property[=].type = #string

