CodeSystem: IMMZ.D1
Title:        "IMMZ.D1 CodeSystem for Data Elements"
Description:  "CodeSystem for IMMZ.D1 Data Elements"

* ^experimental = false
* ^caseSensitive = false
* ^name = "IMMZ_D1"

* #DE109 "Birth dose" "Indicates if the client received a dose within 24 hours of birth. Whether a birth dose is counted as part of the primary series will depend on the antigen."
* #DE103 "Type of dose" "The type of dose in a series that the client received "
* #DE104 "Primary series" "Indicates that the client received the primary vaccination series of a product/antigen. This is also applicable for antigens with one dose."
* #DE105 "Dose 0" "Indicates that the client received a dose of a product/ antigen within 24 hours of birth. This dose is not a part of the primary vaccination series."
* #DE106 "Supplementary dose" "Indicates that the client received a supplementary dose of a product/antigen"
* #DE107 "Booster dose" "Indicates that the client received booster dose of a product/antigen"
* #DE8 "Completed the primary vaccination series" "Indicates if the client has completed the primary vaccination series of a product/antigen. If the client has not yet completed their primary series, it means they may be expected to receive more doses to complete their vaccination regimen for the respective product/antigen."
* #DE102 "Completed the booster series" "Indicates if the client has completed the booster series of a product/antigen"
* #DE81 "Date when primary vaccination series was completed" "The date when the client completed the primary vaccination series (per product/antigen)"
* #DE10 "HIV status" "The current human immunodeficiency virus (HIV) status of the client"
* #DE11 "HIV-positive" "The client is known to be HIV positive"
* #DE12 "HIV-negative" "The client is known to be HIV negative"
* #DE13 "Unknown" "The client's HIV status is unknown"
* #DE15 "Preterm birth" "The infant was preterm; the mother gave birth to the infant when gestational age was less than 37 weeks"
* #DE16 "Immunocompromised" "The client is known to be immunocompromised. This means the client has a weakened immune system and having a reduced ability to fight infections and other diseases"
* #DE17 "Currently on ART" "The client is currently receiving antiretroviral therapy (ART)"
* #DE84 "Type of TB infection test performed" "The type of TB infection test performed"
* #DE85 "IGRA" "Interferon-gamma release assay (IGRA)"
* #DE86 "TST" "Tuberculin skin test (TST) "
* #DE87 "TB infection test result" "Records the result of the TB infection test"
* #DE88 "Positive" "Test result was positive"
* #DE89 "Negative" "Test result was negative"
* #DE93 "Immunologically stable" "The client is living with HIV and is immunologically stable with CD4 count or percentage above a minimum as defined in the HIV guidelines"
* #DE94 "Clinically well" "The client is living with HIV and is clinically well, as defined in HIV guidelines and WHO clinical staging"
* #DE29 "Birth weight in grams" "Represents the client's birth weight value measures in grams"
* #DE35 "Type of polio dose" "The type of the polio vaccine dose administered to the client"
* #DE36 "IPV" "Inactivated poliovirus vaccine (IPV)"
* #DE37 "bOPV" "Bivalent oral poliovirus vaccine (bOPV)"
* #DE92 "Severely immunosuppressed" "The client is known to be severely immunosuppressed"
* #DE49 "ART start date" "The date on which the client started or restarted antiretroviral therapy (ART)"
* #DE96 "High risk of pneumococcal infection " "The client is at high risk for pneumococcal infection because of underlying medical conditions (i.e. HIV infection or sickle-cell disease)"
* #DE52 "Type of JE dose" "The type of Japanese encephalitis (JE) vaccine dose administered to the client"
* #DE53 "Inactivated Vero cell-derived vaccine" "Inactivated Vero cell-derived Japanese encephalitis (JE) vaccine type"
* #DE54 "Live attenuated vaccine" "Live attenuated Japanese encephalitis (JE) vaccine type"
* #DE55 "Live recombinant vaccine" "Live recombinant Japanese encephalitis (JE) vaccine type"
* #DE56 "Type of TBE dose" "The type of tick-borne encephalitis (TBE) vaccine dose administered"
* #DE57 "FSME-Immun" "FSME-Immun vaccine product, which is an inactivated whole-virus vaccine for tick-borne encephalitis (TBE)"
* #DE58 "Encepur" "Encepur vaccine product, which is an inactivated viral vaccine for tick-borne encephalitis (TBE)"
* #DE59 "TBE-Moscow" "TBE-Moscow vaccine product, which is a vaccine for tick-borne encephalitis (TBE)"
* #DE60 "EnceVir" "EnceVir vaccine product, which is a vaccine for tick-borne encephalitis (TBE)"
* #DE61 "Type of typhoid dose" "The type of typhoid vaccine dose administered to the client"
* #DE62 "Typbar-TCV" "Typbar-TCV vaccine"
* #DE63 "ViPS" "Vi polysaccharide (ViPS) vaccine"
* #DE64 "Ty21a" "Ty21a vaccine"
* #DE65 "Type of cholera dose" "The type of cholera vaccine dose administered to the client"
* #DE66 "WC vaccine" "Killed whole cell (WC) only cholera vaccine"
* #DE67 "WC-rBS vaccine" "Vaccine contains a mixture of the recombinant B subunit (rBS) of cholera toxin plus killed whole cell (WC) "
* #DE68 "Type of meningococcal dose" "The type of meningococcal vaccine dose administered to the client"
* #DE69 "MenA conjugate vaccine (5µg)" "Monovalent serogroup A (MenA) conjugate vaccine (5µg) vaccine"
* #DE70 "Monovalent MenC conjugate" "Monovalent MenC conjugate vaccine"
* #DE71 "Quadrivalent conjugate" "Quadrivalent conjugate (A,C,W135,Y-D and A,C,W135,Y-CRM) vaccines"
* #DE97 "Polysaccharide vaccine" "Polysaccharide vaccines not including polysaccharide-protein conjugate vaccines"
* #DE72 "Age in months when client received first meningococcal dose" "The age in months when client received their first meningococcal dose"
* #DE73 "Type of hepatitis A dose" "The type of hepatitis A vaccine dose administered to the client"
* #DE74 "Live attenuated hepatitis A vaccine" "Live attenuated hepatitis A vaccine"
* #DE75 "Inactivated hepatitis A vaccine" "Inactivated hepatitis A vaccine"
* #DE99 "Type of hepatitis B dose" "The type of hepatitis B vaccine dose administered to the client"
* #DE100 "Hepatitis B monovalent vaccine" "Hepatitis B monovalent vaccine"
* #DE101 "Hepatitis B combination vaccine" "Hepatitis B combination vaccine"
* #DE76 "VNA level" "Vaccine-induced neutralizing (VNA) antibody level. It is a measured as a serum antibody concentration amount observed from the result of the concentrated, purified cell culture and embryonated egg-based rabies vaccines (CCEEV)"
* #DE98 "Risk of occupational exposure to rabies virus" "Professional at risk of occupational exposure to rabies virus, particularly animal health-care workers. Also considered for medical professionals who regularly provide care to persons with rabies. "
* #DE77 "Dengue serostatus" "Indicates the result of a serological test determining whether the client has antibodies against the dengue virus"
* #DE110 "Positive" "The client has detectable antibodies against the dengue virus, suggesting past exposure or vaccination"
* #DE111 "Negative" "The client does not have detectable antibodies, indicating no previous exposure or vaccination against the dengue virus"
* #DE112 "Unknown" "The client's dengue serostatus is unknown"
