Profile: DT.IMMZ.D2.DT.Rotavirus
Parent: $SGDecisionTable
Title: "Decision Table Determine required vaccinations"
Description: """Determine required vaccinations"""
* insert SGDecisionTable( IMMZ.D2.DT.Rotavirus,"Determine required vaccinations",0.2.0)


* insert SGDecisionTableOutput("Client is due for rotavirus vaccination","Client is due for rotavirus vaccination","""""")
* insert SGDecisionTableCondition("No rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableGuidance("""Should vaccinate client with  first rotavirus dose as no rotavirus doses were administered, client's age is within appropriate age range and no live vaccine was administered in last 4 weeks.
Check for contraindications.""")
* insert SGDecisionTableCondition("No rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableOutput("Client is not due for rotavirus vaccination","Client is not due for rotavirus vaccination","""""")
* insert SGDecisionTableCondition("No rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableGuidance("""Should not vaccinate client with  first rotavirus dose as live vaccine was administered in last 4 weeks. Check for any vaccines due and inform the caregiver of when to come back for the first dose.""")
* insert SGDecisionTableCondition("No rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableOutput("Client is due for rotavirus vaccination","Client is due for rotavirus vaccination","""A minimum interval of 4 weeks should be maintained between doses.

Note: The rotavirus vaccination series for each child should be completed with the same product whenever feasible. However, if the product used for a prior dose is unavailable or unknown, the series should be completed with any available licensed product.""")
* insert SGDecisionTableCondition("One rotavirus primary series dose was administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableGuidance("""Should vaccinate client with second rotavirus dose as client's age is within appropriate age range and no live vaccine was administered in the last 4 weeks.
Check for contraindications.""")
* insert SGDecisionTableCondition("One rotavirus primary series dose was administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableOutput("Client is not due for rotavirus vaccination","Client is not due for rotavirus vaccination","""""")
* insert SGDecisionTableCondition("One rotavirus primary series dose was administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableGuidance("""Should not vaccinate client with second rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose""")
* insert SGDecisionTableCondition("One rotavirus primary series dose was administered")
* insert SGDecisionTableCondition("Client's age is between 6 weeks and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableOutput("Client is due for rotavirus vaccination","Client is due for rotavirus vaccination","""For a mixed series or a series with any unknown vaccine products, a total of 3 doses of rotavirus vaccine should be administered for a complete vaccination series.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client is a mixed series or a series with unknown vaccine products")
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as no live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series.
Check for contraindications.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in the last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client is a mixed series or a series with unknown vaccine products")
* insert SGDecisionTableOutput("Client is not due for rotavirus vaccination","Client is not due for rotavirus vaccination","""""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("Live vaccines was administered in the last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client is a mixed series or a series with unknown vaccine products")
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series. Check for any other vaccines due and inform the caregiver of when to come back for the next dose""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("Live vaccines was administered in the last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client is a mixed series or a series with unknown vaccine products")
* insert SGDecisionTableOutput("Client is due for rotavirus vaccination","Client is due for rotavirus vaccination","""RotaTeq, Rotavac and Rotasiil should be administered in a 3-dose schedule, while a 2-dose schedule should be used for Rotarix.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain more than two doses")
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as series contains more than two doses and no live vaccine was administered in the last 4 weeks.
Check for contraindications.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("No live vaccine was administered in last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain more than two doses")
* insert SGDecisionTableOutput("Client is not due for rotavirus vaccination","Client is not due for rotavirus vaccination","""""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain more than two doses")
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("Live vaccine was administered in last 4 weeks")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain more than two doses")
* insert SGDecisionTableOutput("Rotavirus immunization schedule is complete","Rotavirus immunization schedule is complete","""""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain less than or equal to two doses")
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Two rotavirus doses were administered. Check for any other vaccines due.""")
* insert SGDecisionTableCondition("Two rotavirus primary series doses were administered")
* insert SGDecisionTableCondition("Client's age is between 6 months and 24 months")
* insert SGDecisionTableCondition("The series administered to the client contains the same product")
* insert SGDecisionTableCondition("The series contain less than or equal to two doses")
* insert SGDecisionTableOutput("Rotavirus immunization schedule is complete","Rotavirus immunization schedule is complete","""–""")
* insert SGDecisionTableCondition("Three rotavirus primary series doses were administered")
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Three rotavirus primary series doses were administered. Check for any other vaccines due.""")
* insert SGDecisionTableCondition("Three rotavirus primary series doses were administered")
* insert SGDecisionTableOutput("Client is not due for rotavirus vaccination if immunization schedule is not complete.","Client is not due for rotavirus vaccination if immunization schedule is not complete.","""Because of the typical age distribution of rotavirus gastroenteritis, rotavirus vaccination of children aged over 24 months is not recommended.""")
* insert SGDecisionTableCondition("Client's age is more than 24 months")
* insert SGDecisionTableGuidance("""Should not vaccinate client with rotavirus dose as client's age is more than 24 months. Check for any other vaccines due.""")
* insert SGDecisionTableCondition("Client's age is more than 24 months")
