Profile: DT.IMMZ.D2.DT.Rotavirus
Parent: $SGDecisionTable
Title: "Decision Table Determine required vaccinations"
Description: """Determine required vaccinations """
* insert SGDecisionTable( IMMZ.D2.DT.Rotavirus,"0.2.0)
* insert SGDecisionTableCitation("""WHO recommendations for routine immunization – summary tables March 2023 1 """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""WHO recommends that the first dose of rotavirus vaccine be administered as soon as possible after 6 weeks of age.  """)
* insert SGDecisionTableCondition("Clientsageislessthan6weeks")
* insert SGDecisionTableGuidance("""Should not vaccinate client with first rotavirus dose as clients age is less than 6 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the first dose. """)
* insert SGDecisionTableCondition("Clientsageislessthan6weeks")
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""  """)
* insert SGDecisionTableCondition("Norotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableGuidance("""Should vaccinate client with  first rotavirus dose as no rotavirus doses were administered\, clients age is within appropriate age range and no live vaccine was administered in last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableCondition("Norotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""  """)
* insert SGDecisionTableCondition("Norotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableGuidance("""Should not vaccinate client with  first rotavirus dose as live vaccine was administered in last 4 weeks. Check for any vaccines due and inform the caregiver of when to come back for the first dose. """)
* insert SGDecisionTableCondition("Norotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""A minimum interval of 4 weeks should be maintained between doses.\n\nNote: The rotavirus vaccination series for each child should be completed with the same product whenever feasible. However\, if the product used for a prior dose is unavailable or unknown\, the series should be completed with any available licensed product.  """)
* insert SGDecisionTableCondition("Onerotavirusprimaryseriesdosewasadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableGuidance("""Should vaccinate client with second rotavirus dose as clients age is within appropriate age range and no live vaccine was administered in the last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableCondition("Onerotavirusprimaryseriesdosewasadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""  """)
* insert SGDecisionTableCondition("Onerotavirusprimaryseriesdosewasadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableGuidance("""Should not vaccinate client with second rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose """)
* insert SGDecisionTableCondition("Onerotavirusprimaryseriesdosewasadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6weeksand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""For a mixed series or a series with any unknown vaccine products\, a total of 3 doses of rotavirus vaccine should be administered for a complete vaccination series.  """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientisamixedseri.5005705dfd")
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as no live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series.\nCheck for contraindications. """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinthelast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientisamixedseri.5005705dfd")
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""  """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Livevaccineswasadministeredinthelast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientisamixedseri.5005705dfd")
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series. Check for any other vaccines due and inform the caregiver of when to come back for the next dose """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Livevaccineswasadministeredinthelast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientisamixedseri.5005705dfd")
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""RotaTeq\, Rotavac and Rotasiil should be administered in a 3-dose schedule\, while a 2-dose schedule should be used for Rotarix.  """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinlast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainmorethantwodoses")
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as series contains more than two doses and no live vaccine was administered in the last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Nolivevaccinewasadministeredinlast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainmorethantwodoses")
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""  """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinlast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainmorethantwodoses")
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose. """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Livevaccinewasadministeredinlast4weeks")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainmorethantwodoses")
* insert SGDecisionTableOutput(DTO.Rotavirusimmunizationscheduleiscomplete,"Rotavirus immunization schedule is complete","""  """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainlessthanorequaltotwodoses")
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Two rotavirus doses were administered. Check for any other vaccines due. """)
* insert SGDecisionTableCondition("Tworotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableCondition("Clientsageisbetween6monthsand24months")
* insert SGDecisionTableCondition("Theseriesadministeredtotheclientcontainsthesameproduct")
* insert SGDecisionTableCondition("Theseriescontainlessthanorequaltotwodoses")
* insert SGDecisionTableOutput(DTO.Rotavirusimmunizationscheduleiscomplete,"Rotavirus immunization schedule is complete","""–  """)
* insert SGDecisionTableCondition("Threerotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Three rotavirus primary series doses were administered. Check for any other vaccines due. """)
* insert SGDecisionTableCondition("Threerotavirusprimaryseriesdoseswereadministered")
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccinationifi.f228e9445e,"Client is not due for rotavirus vaccination if immunization schedule is not complete.","""Because of the typical age distribution of rotavirus gastroenteritis\, rotavirus vaccination of children aged over 24 months is not recommended.  """)
* insert SGDecisionTableCondition("Clientsageismorethan24months")
* insert SGDecisionTableGuidance("""Should not vaccinate client with rotavirus dose as clients age is more than 24 months. Check for any other vaccines due. """)
* insert SGDecisionTableCondition("Clientsageismorethan24months")
