Profile: DT.IMMZ.D2.DT.Rotavirus
Parent: $SGDecisionTable
Title: "Decision Table Determine required vaccinations"
Description: """Determine required vaccinations """
* insert SGDecisionTable( DT.IMMZ.D2.DT.Rotavirus,0.2.0)

* insert SGDecisionTableCitation("""WHO recommendations for routine immunization – summary tables March 2023 1 """)
* insert SGDecisionTableCitation("""References """)
* insert SGDecisionTableCitation("""WHO recommendations for routine immunization – summary tables March 2023 1 """)
* insert SGDecisionTableCitation("""WHO recommendations for routine immunization – summary tables March 2023 1\nRotavirus vaccines: WHO position paper July 2021 12 """)
* insert SGDecisionTableCitation("""WHO recommendations for routine immunization – summary tables March 2023 1 """)

* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination","""WHO recommends that the first dose of rotavirus vaccine be administered as soon as possible after 6 weeks of age.  """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with first rotavirus dose as clients age is less than 6 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the first dose. """)
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination",""" """)
* insert SGDecisionTableGuidance("""Should vaccinate client with  first rotavirus dose as no rotavirus doses were administered\, clients age is within appropriate age range and no live vaccine was administered in last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination",""" """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with  first rotavirus dose as live vaccine was administered in last 4 weeks. Check for any vaccines due and inform the caregiver of when to come back for the first dose. """)
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""A minimum interval of 4 weeks should be maintained between doses.\n\nNote: The rotavirus vaccination series for each child should be completed with the same product whenever feasible. However\, if the product used for a prior dose is unavailable or unknown\, the series should be completed with any available licensed product.  """)
* insert SGDecisionTableGuidance("""Should vaccinate client with second rotavirus dose as clients age is within appropriate age range and no live vaccine was administered in the last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination",""" """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with second rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose """)
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""For a mixed series or a series with any unknown vaccine products\, a total of 3 doses of rotavirus vaccine should be administered for a complete vaccination series.  """)
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as no live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series.\nCheck for contraindications. """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination",""" """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks and series administered to client is a mixed or unknown series. Check for any other vaccines due and inform the caregiver of when to come back for the next dose """)
* insert SGDecisionTableOutput(DTO.Clientisdueforrotavirusvaccination,"Client is due for rotavirus vaccination","""RotaTeq\, Rotavac and Rotasiil should be administered in a 3-dose schedule\, while a 2-dose schedule should be used for Rotarix.  """)
* insert SGDecisionTableGuidance("""Should vaccinate client with third rotavirus dose as series contains more than two doses and no live vaccine was administered in the last 4 weeks.\nCheck for contraindications. """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccination,"Client is not due for rotavirus vaccination",""" """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with third rotavirus dose as live vaccine was administered in the last 4 weeks. Check for any other vaccines due and inform the caregiver of when to come back for the next dose. """)
* insert SGDecisionTableOutput(DTO.Rotavirusimmunizationscheduleiscomplete,"Rotavirus immunization schedule is complete",""" """)
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Two rotavirus doses were administered. Check for any other vaccines due. """)
* insert SGDecisionTableOutput(DTO.Rotavirusimmunizationscheduleiscomplete,"Rotavirus immunization schedule is complete","""–  """)
* insert SGDecisionTableGuidance("""Rotavirus immunization schedule is complete. Three rotavirus primary series doses were administered. Check for any other vaccines due. """)
* insert SGDecisionTableOutput(DTO.Clientisnotdueforrotavirusvaccinationifi.f228e9445e,"Client is not due for rotavirus vaccination if immunization schedule is not complete.","""Because of the typical age distribution of rotavirus gastroenteritis\, rotavirus vaccination of children aged over 24 months is not recommended.  """)
* insert SGDecisionTableGuidance("""Should not vaccinate client with rotavirus dose as clients age is more than 24 months. Check for any other vaccines due. """)
* insert SGDecisionTableOutput(DTO.None,"None",""" """)
* insert SGDecisionTableOutput(DTO.None,"None",""" """)
* insert SGDecisionTableOutput(DTO.None,"None",""" """)
* insert SGDecisionTableOutput(DTO.Output,"Output","""Annotations  """)
* insert SGDecisionTableGuidance("""Guidance displayed to health worker """)
* insert SGDecisionTableOutput(DTO.Rotavirusvaccinationiscontraindicated,"Rotavirus vaccination is contraindicated","""–  """)
* insert SGDecisionTableGuidance("""Do not vaccinate client with rotavirus as rotavirus vaccination is contraindicated for clients with prior history of intussusception. """)
* insert SGDecisionTableOutput(DTO.Rotavirusvaccinationiscontraindicated,"Rotavirus vaccination is contraindicated","""–  """)
* insert SGDecisionTableGuidance("""Do not vaccinate client with rotavirus as rotavirus vaccincation is contraindicated for clients with severe immunodeficiency\, including severe combined immunodeficiency. """)
* insert SGDecisionTableOutput(DTO.Rotavirusvaccinationcouldbecontraindicat.0d054e1b28,"Rotavirus vaccination could be contraindicated. Clinical judgement is required. Create a clinical note","""Rotavirus vaccine should not be given to children with severe allergic reaction e.g. anaphylaxis after a previous dose.\nContraindications for using rotavirus vaccines are severe hypersensitivity to any of their components including severe combined immunodeficiency.  """)
* insert SGDecisionTableGuidance("""Do not vaccinate client with rotavirus if client had severe allergic reactions to a previous rotavirus vaccine dose or rotavirus vaccine components.\nCheck if the client has no known severe hypersensitivity to rotavirus vaccines components. """)
* insert SGDecisionTableOutput(DTO.Rotavirusvaccinationcouldbecontraindicat.0d054e1b28,"Rotavirus vaccination could be contraindicated. Clinical judgement is required. Create a clinical note",""" """)
* insert SGDecisionTableGuidance("""Do not vaccinate client with rotavirus if client has history of anaphylactic reaction to a previous rotavirus vaccine dose or rotavirus vaccine components. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has altered immunocompetence other than severe combined immunodeficiency\, consider risks of vaccination and make a judgement. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has spina bifida\, consider risks of vaccination and make a judgement. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has bladder exstrophy\, consider risks of vaccination and make a judgement. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has chronic gastrointestinal disease\, consider risks of vaccination and make a judgement. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has acute gastroenteritis\, consider risks of vaccination and make a judgement. Consider delaying rotavirus vaccination. """)
* insert SGDecisionTableOutput(DTO.Clinicaljudgementisrequired.Createaclinicalnote,"Clinical judgement is required. Create a clinical note","""–  """)
* insert SGDecisionTableGuidance("""Client has moderate to severe fever\, consider risks of vaccination and make a judgement. Consider delaying rotavirus vaccination. """)
* insert SGDecisionTableOutput(DTO.None,"None","""Note: While vaccines are universally recommended\, some clients may have contraindications to particular vaccines. Additional contraindications may be included in WHO position paper for the vaccine – Rotavirus vaccines: WHO position paper July 2021 12.  """)

