
@host = http://localhost:8080/matchboxv3/fhir

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-C-QRToLM.fml

### Test Transform of QR to LM
### after running sushi
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCQRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json

### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZCRegisterClient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/StructureDefinition-IMMZCRegisterClient.json

### Get structure def
GET {{host}}/StructureDefinition/IMMZCRegisterClient HTTP/1.1

### POST ConceptMap
PUT {{host}}/ConceptMap/IMMZ.C.SexToAdministrativeGender HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/ConceptMap-IMMZ.C.SexToAdministrativeGender.json

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-LMToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-C-LMToPatient.fml

### Test Transform of LM to Patient
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCLMToPatient
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./example-IMMZ-C-register-client-1.json

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-QRToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-C-QRToPatient.fml

### Test Transform of QR to Patient
### after running sushi
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCQRToPatient
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json



### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD4QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D4-QRToLM.fml

### Test Transform of QR to LM
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD4QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D4.QuestionnaireResponse.4.json

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD4LMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D4-LMToResources.fml

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD4QRToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D4-QRToResources.fml

### Test Transform of QR to Bundle
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD4QRToResources
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D4.QuestionnaireResponse.4.json



### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZD1ClientHistoryMeasles HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/StructureDefinition-IMMZD1ClientHistoryMeasles.json

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD1QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D1-QRToLM.fml

### Test Transform of QR to LM
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.2.json

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1LMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D1-LMToResources.fml

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1QRToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ-D1-QRToResources.fml

### Test Transform of QR to Resources
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1QRToResources
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.3.json