
@host = http://localhost:8080/matchboxv3/fhir

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZCQRToLM.fml

### Test Transform of QR to LM
### after running sushi
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCQRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json

### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZCRegisterClient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/StructureDefinition-IMMZCRegisterClient.json

### Get structure def
GET {{host}}/StructureDefinition/IMMZCRegisterClient HTTP/1.1

### POST ConceptMap
PUT {{host}}/ConceptMap/IMMZ.C.SexToAdministrativeGender HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/ConceptMap-IMMZ.C.SexToAdministrativeGender.json

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-LMToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZCLMToPatient.fml

### Test Transform of LM to Patient
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCLMToPatient
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ./example-IMMZ-C-register-client-1.json

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ-C-QRToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZCQRToPatient.fml

### Test Transform of QR to Patient
### after running sushi
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZCQRToPatient
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json



### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD5QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD5QRToLM.fml

### Test Transform of QR to LM
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD5QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D5.QuestionnaireResponse.4.json

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD5LMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD5LMToResources.fml

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD5QRToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD5QRToResources.fml

### Test Transform of QR to Bundle
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD5QRToResources
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D5.QuestionnaireResponse.4.json



### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZD1ClientHistory HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/StructureDefinition-IMMZD1ClientHistory.json


### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZD1ClientHistoryMeasles HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/StructureDefinition-IMMZD1ClientHistoryMeasles.json


### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD1QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1QRToLM.fml

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1LMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1LMToResources.fml

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD1MeaslesQRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1MeaslesQRToLM.fml

### Test Transform of QR to LM
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1MeaslesQRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.3.json

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1MeaslesLMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1MeaslesLMToResources.fml

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1MeaslesQRToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1MeaslesQRToResources.fml

### Test Transform of QR to Resources
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1MeaslesQRToResources
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.3.json



### POST Logical Model
PUT {{host}}/StructureDefinition/IMMZD1ClientHistoryPolio HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/StructureDefinition-IMMZD1ClientHistoryPolio.json

### Post the StructureMap for Contraindications with transform included
PUT {{host}}/StructureMap/IMMZD1PolioQRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1PolioQRToLM.fml

### Test Transform of QR to LM
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1PolioQRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.Polio.json

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1PolioLMToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1PolioLMToResources.fml

### Post the StructureMap for Client History with transform included
PUT {{host}}/StructureMap/IMMZD1PolioQRToResources HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZD1PolioQRToResources.fml

### Test Transform of QR to Resources
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/ig/smart-immunizations/StructureMap/IMMZD1PolioQRToResources
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.Polio.json