@host = http://localhost:8080/matchboxv3/fhir

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.Helpers HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.Helpers.fml


### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.C4.QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.C4.QRToLM.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.C4.LMToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.C4.LMToPatient.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.C4.QRToPatient HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.C4.QRToPatient.fml

### Test Transform of QR to LM
### after running _getonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.C4.QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json

### Test Transform of QR to LM
### after running _genonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.C4.QRToPatient
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../output/QuestionnaireResponse-Example.IMMZ.C.QuestionnaireResponse.1.json


### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D1.QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D1.QRToLM.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D1.LMToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D1.LMToBundle.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D1.QRToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D1.QRToBundle.fml

### Test Transform of QR to LM
### after running _getonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D1.QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.BCG.json

### Test Transform of QR to LM
### after running _genonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D1.QRToBundle
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D1.QuestionnaireResponse.BCG.json


### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D13.QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D13.QRToLM.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D13.LMToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D13.LMToBundle.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D13.QRToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D13.QRToBundle.fml

### Test Transform of QR to LM
### after running _getonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D13.QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D13.QuestionnaireResponse.BCG.json

### Test Transform of QR to LM
### after running _genonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D13.QRToBundle
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D13.QuestionnaireResponse.BCG.json


### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D5.QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D5.QRToLM.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D5.LMToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D5.LMToBundle.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D5.QRToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D5.QRToBundle.fml

### Test Transform of QR to LM
### after running _getonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D5.QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D5.QuestionnaireResponse.1.json

### Test Transform of QR to LM
### after running _genonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D5.QRToBundle
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D5.QuestionnaireResponse.1.json



### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D17.QRToLM HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D17.QRToLM.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D17.LMToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D17.LMToBundle.fml

### Post the StructureMap with transform included
PUT {{host}}/StructureMap/IMMZ.D17.QRToBundle HTTP/1.1
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: text/fhir-mapping

< ../input/maps/IMMZ.D17.QRToBundle.fml

### Test Transform of QR to LM
### after running _getonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D17.QRToLM
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D17.QuestionnaireResponse.1.json

### Test Transform of QR to LM
### after running _genonce
POST {{host}}/StructureMap/$transform?source=http://smart.who.int/immunizations/StructureMap/IMMZ.D17.QRToBundle
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0

< ../fsh-generated/resources/QuestionnaireResponse-Example.IMMZ.D17.QuestionnaireResponse.1.json